#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  vim:ts=4:sts=4:sw=4:et

language: python
python:
  - "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  #- "3.5"
  - "pypy"
  #- "pypy3"

sudo: required

notifications:
  email: false

branches:
  only:
    - master

install:
  - make
  - pip install codecov
  - pip install coveralls

script:
  - make test
  - coverage run --source=harisekhon,harisekhon/nagiosplugin -m test

after_success:
  - coveralls
#  - codecov
